token_configuration:
  access_token_duration: 600s
  refresh_token_duration: 2592000s
http:
  host: "0.0.0.0"
  port: "8080"
pg:
  user: "postgres"
  password: "1234"
  host: "localhost"
  port: "5432"
  database: "auth"
  pool_max: "6"
  migrations_path: "file://config/pg/migrations"
jwt:
  secret_key: "someSuperStrongKey"
cookie:
  domain: "localhost"
  path: "/"
  secure: false
  http_only: true
  same_site: "lax"
